cloud:
  aws:
    credentials:
      access-key: "Enter aws access key"
      secret-key: "Enter aws secret key"
    region:
      static: eu-north-1
    stack:
      auto: false

application:
  bucket:
    name: onlinequizresults

#spring:#  servlet:#    multipart:#      enabled: true
#      file-size-threshold: 2MB#      max-file-size: 5MB#      max-request-size: 10MB
      server:  port: 9990     